version: "3.9"

services:
  api:
    build: .
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./finance.db:/app/finance.db
    command: uvicorn main:app --host 0.0.0.0 --port 8001

  streamlit:
    build: .
    depends_on:
      - api
    environment:
      - API_BASE_URL=http://api:8001
    ports:
      - "8501:8501"
    command: streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    volumes:
      - ./data:/app/data
